In [1]:
import sys

print(sys.executable)

D:\CODING\Modelling\.venv\Scripts\python.exe

In [8]:
import pandas as pd

occurrence = pd.read_csv("Occurance.csv")
conditions = pd.read_csv("Condition_Factors.csv")

print("Occurrence records:", len(occurrence))
print("Condition-factor records:", len(conditions))

Occurrence records: 136
Condition-factor records: 65535

In [9]:
print("OCCURRENCE COLUMNS:")
print(occurrence.columns.tolist())

print("\nCONDITION-FACTOR COLUMNS:")
print(conditions.columns.tolist())

OCCURRENCE COLUMNS:
['Longitude', 'Latitude', 'year', 'TaxonName', 'field_5', 'OBJECTID', 'Longitude_', 'Latitude_2', 'Presence']

CONDITION-FACTOR COLUMNS:
['OBJECTID', 'Longitude', 'Latitude', 'NDVI_1995', 'NDVI_2005', 'NDVI_2015', 'NDVI_2025', 'PCI_1995', 'PCI_2005', 'PCI_2015', 'PCI_2025', 'VHI_1995', 'VHI_2005', 'VHI_2015', 'VHI_2025', 'TCI_1995', 'TCI_2005', 'TCI_2015', 'TCI_2025', 'NDBI_1995', 'NDBI_2005', 'NDBI_2015', 'NDBI_2025', 'NDMI_1995', 'NDMI_2005', 'NDMI_2015', 'NDMI_2025', 'SAVI_1995', 'SAVI_2005', 'SAVI_2015', 'SAVI_2025', 'LST_1995', 'LST_2005', 'LST_2015', 'LST_2025', 'SMI_1995', 'SMI_2005', 'SMI_2015', 'SMI_2025', 'pop_1995', 'pop_2005', 'pop_2015', 'pop_2025', 'SOC', 'Aspect', 'Slope', 'PH', 'TRI', 'TWI', 'Nyeri_LULC_1995', 'Nyeri_LULC_2005', 'Nyeri_LULC_2015', 'Nyeri_LULC_2025', 'rain_1995', 'rain_2005', 'rain_2015', 'rain_2025']

In [10]:
print("OCCURRENCE DATA TYPES")
print(occurrence.dtypes)

print("\nCONDITION-FACTOR DATA TYPES")
print(conditions.dtypes)

print("\nOCCURRENCE RECORDS")
print(len(occurrence))

print("\nCONDITION-FACTOR RECORDS")
print(len(conditions))

OCCURRENCE DATA TYPES
Longitude     float64
Latitude      float64
year            int64
TaxonName         str
field_5           str
OBJECTID        int64
Longitude_    float64
Latitude_2    float64
Presence        int64
dtype: object

CONDITION-FACTOR DATA TYPES
OBJECTID           float64
Longitude          float64
Latitude           float64
NDVI_1995          float64
NDVI_2005          float64
NDVI_2015          float64
NDVI_2025          float64
PCI_1995           float64
PCI_2005           float64
PCI_2015           float64
PCI_2025           float64
VHI_1995           float64
VHI_2005           float64
VHI_2015           float64
VHI_2025           float64
TCI_1995           float64
TCI_2005           float64
TCI_2015           float64
TCI_2025           float64
NDBI_1995          float64
NDBI_2005          float64
NDBI_2015          float64
NDBI_2025          float64
NDMI_1995          float64
NDMI_2005          float64
NDMI_2015          float64
NDMI_2025          float64
SAVI_1995          float64
SAVI_2005          float64
SAVI_2015          float64
SAVI_2025          float64
LST_1995           float64
LST_2005           float64
LST_2015           float64
LST_2025           float64
SMI_1995           float64
SMI_2005           float64
SMI_2015           float64
SMI_2025           float64
pop_1995           float64
pop_2005           float64
pop_2015           float64
pop_2025           float64
SOC                float64
Aspect             float64
Slope              float64
PH                 float64
TRI                float64
TWI                float64
Nyeri_LULC_1995    float64
Nyeri_LULC_2005    float64
Nyeri_LULC_2015    float64
Nyeri_LULC_2025    float64
rain_1995          float64
rain_2005          float64
rain_2015          float64
rain_2025          float64
dtype: object

OCCURRENCE RECORDS
136

CONDITION-FACTOR RECORDS
65535

In [11]:
print("Occurrence OBJECTID examples:")
print(occurrence["OBJECTID"].head(10).to_list())

print("\nCondition-factor OBJECTID examples:")
print(conditions["OBJECTID"].head(10).to_list())

Occurrence OBJECTID examples:
[763, 763, 763, 763, 268, 1795, 1795, 1795, 3282, 2121]

Condition-factor OBJECTID examples:
[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]

In [12]:
# Make working copies
occ = occurrence.copy()
factors = conditions.copy()

# Standardize OBJECTID
occ["OBJECTID"] = pd.to_numeric(occ["OBJECTID"], errors="coerce").astype("Int64")
factors["OBJECTID"] = pd.to_numeric(factors["OBJECTID"], errors="coerce").astype("Int64")

print("Occurrence OBJECTID type:", occ["OBJECTID"].dtype)
print("Condition-factor OBJECTID type:", factors["OBJECTID"].dtype)

print("\nOccurrence records:", len(occ))
print("Condition-factor records:", len(factors))

Occurrence OBJECTID type: Int64
Condition-factor OBJECTID type: Int64

Occurrence records: 136
Condition-factor records: 65535

In [13]:
missing_ids = occ.loc[
    ~occ["OBJECTID"].isin(factors["OBJECTID"]),
    "OBJECTID"
].unique()

print("Occurrence OBJECTIDs not found in condition factors:")
print(missing_ids)

print("\nNumber of missing OBJECTIDs:", len(missing_ids))

Occurrence OBJECTIDs not found in condition factors:
<IntegerArray>
[]
Length: 0, dtype: Int64

Number of missing OBJECTIDs: 0

In [14]:
merged = occ.merge(
    factors,
    on="OBJECTID",
    how="left",
    suffixes=("_occ", "_factor")
)

print("Merged records:", len(merged))
print("Merged columns:", len(merged.columns))

Merged records: 136
Merged columns: 65

In [15]:
years = [1995, 2005, 2015, 2025]

dynamic_variables = [
    "NDVI",
    "PCI",
    "VHI",
    "TCI",
    "NDBI",
    "NDMI",
    "SAVI",
    "LST",
    "SMI",
    "pop",
    "rain"
]

for var in dynamic_variables:
    merged[var] = pd.NA
    
    for year in years:
        source_column = f"{var}_{year}"
        mask = merged["year"] == year
        
        merged.loc[mask, var] = merged.loc[mask, source_column]

print("Year-specific environmental variables created successfully.")

Year-specific environmental variables created successfully.

In [16]:
merged["LULC"] = pd.NA

for year in years:
    source_column = f"Nyeri_LULC_{year}"
    mask = merged["year"] == year
    
    merged.loc[mask, "LULC"] = merged.loc[mask, source_column]

print("LULC variable created successfully.")

LULC variable created successfully.

In [17]:
merged[
    ["OBJECTID", "Longitude", "Latitude", "year",
     "NDVI", "PCI", "VHI", "TCI", "LST",
     "LULC", "rain"]
].head(10)

KeyError: "['Longitude', 'Latitude'] not in index"

In [18]:
print(merged.columns.tolist())

['Longitude_occ', 'Latitude_occ', 'year', 'TaxonName', 'field_5', 'OBJECTID', 'Longitude_', 'Latitude_2', 'Presence', 'Longitude_factor', 'Latitude_factor', 'NDVI_1995', 'NDVI_2005', 'NDVI_2015', 'NDVI_2025', 'PCI_1995', 'PCI_2005', 'PCI_2015', 'PCI_2025', 'VHI_1995', 'VHI_2005', 'VHI_2015', 'VHI_2025', 'TCI_1995', 'TCI_2005', 'TCI_2015', 'TCI_2025', 'NDBI_1995', 'NDBI_2005', 'NDBI_2015', 'NDBI_2025', 'NDMI_1995', 'NDMI_2005', 'NDMI_2015', 'NDMI_2025', 'SAVI_1995', 'SAVI_2005', 'SAVI_2015', 'SAVI_2025', 'LST_1995', 'LST_2005', 'LST_2015', 'LST_2025', 'SMI_1995', 'SMI_2005', 'SMI_2015', 'SMI_2025', 'pop_1995', 'pop_2005', 'pop_2015', 'pop_2025', 'SOC', 'Aspect', 'Slope', 'PH', 'TRI', 'TWI', 'Nyeri_LULC_1995', 'Nyeri_LULC_2005', 'Nyeri_LULC_2015', 'Nyeri_LULC_2025', 'rain_1995', 'rain_2005', 'rain_2015', 'rain_2025', 'NDVI', 'PCI', 'VHI', 'TCI', 'NDBI', 'NDMI', 'SAVI', 'LST', 'SMI', 'pop', 'rain', 'LULC']

In [19]:
merged[
    ["OBJECTID", "Longitude_occ", "Latitude_occ", "year",
     "NDVI", "PCI", "VHI", "TCI", "LST",
     "LULC", "rain"]
].head(10)

,OBJECTID,Longitude_occ,Latitude_occ,year,NDVI,PCI,VHI,TCI,LST,LULC,rain
0,763,37.000000,-0.633333,1995,0.547744,40.56507,49.27619,0.40443,27.570998,4.0,1591.478027
1,763,37.000000,-0.633330,1995,0.547744,40.56507,49.27619,0.40443,27.570998,4.0,1591.478027
2,763,37.000000,-0.633330,1995,0.547744,40.56507,49.27619,0.40443,27.570998,4.0,1591.478027
3,763,37.000000,-0.633330,1995,0.547744,40.56507,49.27619,0.40443,27.570998,4.0,1591.478027
4,268,37.133333,-0.316667,1995,0.816245,41.613003,73.779236,0.609076,19.859872,0.0,1201.499878
5,1795,36.831490,-0.347810,1995,0.811382,40.421284,71.112494,0.56091,21.674778,0.0,1270.514771
6,1795,36.831490,-0.347810,1995,0.811382,40.421284,71.112494,0.56091,21.674778,0.0,1270.514771
7,1795,36.831490,-0.347810,1995,0.811382,40.421284,71.112494,0.56091,21.674778,0.0,1270.514771
8,3282,36.666699,-0.416903,1995,0.727109,39.51131,76.710399,0.76245,14.080707,0.0,1812.491089
9,2121,36.935456,-0.420150,1995,0.580975,41.251748,55.642142,0.496424,24.10463,2.0,1178.557617

In [20]:
final_columns = [
    "OBJECTID",
    "Longitude_occ",
    "Latitude_occ",
    "year",
    "TaxonName",
    "NDVI",
    "PCI",
    "VHI",
    "TCI",
    "NDBI",
    "NDMI",
    "SAVI",
    "LST",
    "SMI",
    "pop",
    "SOC",
    "Aspect",
    "Slope",
    "PH",
    "TRI",
    "TWI",
    "LULC",
    "rain",
    "Presence"
]

final = merged[final_columns].copy()

# Rename the original GBIF coordinates
final = final.rename(columns={
    "Longitude_occ": "Longitude",
    "Latitude_occ": "Latitude"
})

print("Final records:", len(final))
print("Final columns:", len(final.columns))

print("\nColumns:")
print(final.columns.tolist())

Final records: 136
Final columns: 24

Columns:
['OBJECTID', 'Longitude', 'Latitude', 'year', 'TaxonName', 'NDVI', 'PCI', 'VHI', 'TCI', 'NDBI', 'NDMI', 'SAVI', 'LST', 'SMI', 'pop', 'SOC', 'Aspect', 'Slope', 'PH', 'TRI', 'TWI', 'LULC', 'rain', 'Presence']

In [21]:
final.head(10)

,OBJECTID,Longitude,Latitude,year,TaxonName,NDVI,PCI,VHI,TCI,NDBI,...,pop,SOC,Aspect,Slope,PH,TRI,TWI,LULC,rain,Presence
0,763,37.000000,-0.633333,1995,polyrhachis viscosa,0.547744,40.56507,49.27619,0.40443,0.190476,...,360.981494,42.948906,204.373871,13.032513,5.407969,0.623312,NaN,4.0,1591.478027,1
1,763,37.000000,-0.633330,1995,tetraponera parops,0.547744,40.56507,49.27619,0.40443,0.190476,...,360.981494,42.948906,204.373871,13.032513,5.407969,0.623312,NaN,4.0,1591.478027,1
2,763,37.000000,-0.633330,1995,tetraponera ambigua,0.547744,40.56507,49.27619,0.40443,0.190476,...,360.981494,42.948906,204.373871,13.032513,5.407969,0.623312,NaN,4.0,1591.478027,1
3,763,37.000000,-0.633330,1995,tetraponera gerdae,0.547744,40.56507,49.27619,0.40443,0.190476,...,360.981494,42.948906,204.373871,13.032513,5.407969,0.623312,NaN,4.0,1591.478027,1
4,268,37.133333,-0.316667,1995,Oligositoides semicinctum,0.816245,41.613003,73.779236,0.609076,0.396618,...,32.775685,48.015175,168.618957,10.947790,5.459834,0.676440,3.885907,0.0,1201.499878,1
5,1795,36.831490,-0.347810,1995,strumigenys katapelta,0.811382,40.421284,71.112494,0.56091,0.37178,...,0.098134,46.718647,119.377029,11.003533,5.300000,0.433929,2.850979,0.0,1270.514771,1
6,1795,36.831490,-0.347810,1995,hypoponera segnis,0.811382,40.421284,71.112494,0.56091,0.37178,...,0.098134,46.718647,119.377029,11.003533,5.300000,0.433929,2.850979,0.0,1270.514771,1
7,1795,36.831490,-0.347810,1995,discothyrea dryad,0.811382,40.421284,71.112494,0.56091,0.37178,...,0.098134,46.718647,119.377029,11.003533,5.300000,0.433929,2.850979,0.0,1270.514771,1
8,3282,36.666699,-0.416903,1995,"Dorylus molestus (Gerstacker, 1859) = Dorylus ...",0.727109,39.51131,76.710399,0.76245,0.215271,...,0.0,83.469872,174.910065,16.475666,5.220391,0.994688,2.494570,0.0,1812.491089,1
9,2121,36.935456,-0.420150,1995,"Anomma nigricans (Illiger, 1802) = Dorylus nig...",0.580975,41.251748,55.642142,0.496424,0.153151,...,2171.785656,32.265972,147.774490,10.435356,5.845007,0.810918,8.761285,2.0,1178.557617,1

In [22]:
missing = final.isna().sum()

print("Missing values by column:")
print(missing[missing > 0])

print("\nTotal missing values:", missing.sum())

Missing values by column:
VHI      4
TCI      4
LST      4
SMI      4
pop      1
TWI     30
rain    35
dtype: int64

Total missing values: 82

In [23]:
print("\nRecords containing any missing value:")
print(final[final.isna().any(axis=1)].to_string())

Records containing any missing value:
     OBJECTID  Longitude  Latitude  year                                                                    TaxonName      NDVI        PCI        VHI       TCI      NDBI      NDMI      SAVI        LST       SMI          pop        SOC      Aspect      Slope        PH       TRI       TWI LULC         rain  Presence
0         763  37.000000 -0.633333  1995                                                          polyrhachis viscosa  0.547744   40.56507   49.27619   0.40443  0.190476  0.190476  0.300664  27.570998   0.40443   360.981494  42.948906  204.373871  13.032513  5.407969  0.623312       NaN  4.0  1591.478027         1
1         763  37.000000 -0.633330  1995                                                           tetraponera parops  0.547744   40.56507   49.27619   0.40443  0.190476  0.190476  0.300664  27.570998   0.40443   360.981494  42.948906  204.373871  13.032513  5.407969  0.623312       NaN  4.0  1591.478027         1
2         763  37.000000 -0.633330  1995                                                          tetraponera ambigua  0.547744   40.56507   49.27619   0.40443  0.190476  0.190476  0.300664  27.570998   0.40443   360.981494  42.948906  204.373871  13.032513  5.407969  0.623312       NaN  4.0  1591.478027         1
3         763  37.000000 -0.633330  1995                                                           tetraponera gerdae  0.547744   40.56507   49.27619   0.40443  0.190476  0.190476  0.300664  27.570998   0.40443   360.981494  42.948906  204.373871  13.032513  5.407969  0.623312       NaN  4.0  1591.478027         1
10       2544  36.635714 -0.546953  1995         Anomma nigricans (Illiger, 1802) = Dorylus nigricans (Illiger, 1802)  0.737784  39.282827  77.878495  0.774465  0.190369  0.190369  0.388026  13.627992  0.774465          0.0  64.713127  115.625153   7.896955  5.263845  0.785643       NaN  0.0  1730.248047         1
11       4593  37.219867 -0.664578  1995         Anomma nigricans (Illiger, 1802) = Dorylus nigricans (Illiger, 1802)   0.49437  40.113191  43.099125  0.337624  0.075425  0.075425  0.329312  30.088249  0.337624   207.084081  35.148525   78.506844  18.150137  6.031483  0.459561  8.696597  4.0          NaN         1
16       2544  36.635714 -0.546953  1995  Technomyrmex detorquens (Walker, 1859) = Technomyrmex albipes (Smith, 1861)  0.737784  39.282827  77.878495  0.774465  0.190369  0.190369  0.388026  13.627992  0.774465          0.0  64.713127  115.625153   7.896955  5.263845  0.785643       NaN  0.0  1730.248047         1
17       4377  37.300000 -0.150000  1995                                                               Apis mellifera  0.118741   39.56874  46.311789  0.801169 -0.181554 -0.181554  0.042595   12.62179  0.801169     0.001029  44.341511  327.777222  38.848415  5.600000  2.836613  1.378922  2.0          NaN         1
18       4774  37.308410 -0.152140  1995                                              Boltonopone soror (Emery, 1899)  0.167722  39.636415   57.66723  0.981676 -0.218344 -0.218344  0.034226    5.82021  0.981676      0.00023  47.315350  156.754334   7.426434  5.609660  2.212738  1.478975  2.0          NaN         1
19       4774  37.333332 -0.166667  1995                                          Belonogaster pennata Richards, 1982  0.167722  39.636415   57.66723  0.981676 -0.218344 -0.218344  0.034226    5.82021  0.981676      0.00023  47.315350  156.754334   7.426434  5.609660  2.212738  1.478975  2.0          NaN         1
20       4758  37.233334 -0.416667  1995                     Ancistrocerus neuvillei (Buysson, 1906) subsp. neuvillei   0.79741  42.224791  74.472339   0.64296  0.398696  0.398696  0.476944  18.583141   0.64296          NaN  51.375164  208.758270   9.942536  5.300000  0.540889       NaN  1.0          NaN         1
23       4252  37.300000 -0.270000  1995                                                     Pteromalus Swederus 1795   0.49358  41.162658   62.60534  0.728589  0.048044  0.048044  0.292732  15.356623  0.728589      0.00068  82.973686  171.246597  24.025703  5.324329  0.218313       NaN  2.0          NaN         1
26       4823  36.913600  0.021800  2005                                                           Distega carbonaria  0.579919  14.451371  49.762622  0.369885  0.103995  0.103995  0.351614  30.204744  0.369885   219.799866  25.002163  249.506058   3.460222  7.103400  0.396991       NaN  1.0          NaN         1
27       4823  36.913630  0.021770  2005                                                                     Aleiodes  0.579919  14.451371  49.762622  0.369885  0.103995  0.103995  0.351614  30.204744  0.369885   219.799866  25.002163  249.506058   3.460222  7.103400  0.396991       NaN  1.0          NaN         1
30       4823  36.913630  0.021700  2005                                                                     Cremnops  0.579919  14.451371  49.762622  0.369885  0.103995  0.103995  0.351614  30.204744  0.369885   219.799866  25.002163  249.506058   3.460222  7.103400  0.396991       NaN  1.0          NaN         1
46       4194  37.310223 -0.465306  2005                                                                 BOLD:ACE2866  0.816875  15.621821  72.059958  0.545147  0.352071  0.352071  0.466129  23.194646  0.545147     15.11375  47.284016  156.408356   7.988733  5.235861  0.853780       NaN  0.0          NaN         1
47       4194  37.310223 -0.465306  2005                                                                 BOLD:ADZ2287  0.816875  15.621821  72.059958  0.545147  0.352071  0.352071  0.466129  23.194646  0.545147     15.11375  47.284016  156.408356   7.988733  5.235861  0.853780       NaN  0.0          NaN         1
48       4194  37.310223 -0.465306  2005                                                                 BOLD:ACB7660  0.816875  15.621821  72.059958  0.545147  0.352071  0.352071  0.466129  23.194646  0.545147     15.11375  47.284016  156.408356   7.988733  5.235861  0.853780       NaN  0.0          NaN         1
50       4910  37.066667  0.016667  2005                                                Megachile nasalis Smith, 1879  0.389213  14.930837  28.753335  0.170304 -0.004664 -0.004664  0.242506  38.187496  0.170304  2209.459229  26.110956  114.179909   2.207784  7.159570  0.175606       NaN  4.0          NaN         1
58       4809  36.997833  0.012955  2005                                                  Camponotus sp. (Mayr, 1861)  0.319454  14.784978  20.335179  0.073318 -0.142939 -0.142939  0.209174  42.066713  0.073318   149.888016  24.625547  162.345108   4.342700  6.976662  0.490733  6.152721  4.0          NaN         1
62       4956  36.903223  0.026475  2015                                                          Sceliphron spirifex  0.516521  45.334882  37.787481  0.161286  0.089899  0.089899  0.333192  38.547056  0.161286   269.598175  25.000000  200.576340   3.073024  7.113849  0.997912       NaN  4.0          NaN         1
63       4956  36.903052  0.027349  2015                                                    Apis mellifera scutellata  0.516521  45.334882  37.787481  0.161286  0.089899  0.089899  0.333192  38.547056  0.161286   269.598175  25.000000  200.576340   3.073024  7.113849  0.997912       NaN  4.0          NaN         1
64       4910  37.076938  0.002412  2015                                                               Apis mellifera  0.267927  46.898955  22.216203  0.183497 -0.009885 -0.009885  0.177402  37.658747  0.183497  3294.163086  26.110956  114.179909   2.207784  7.159570  0.175606       NaN  4.0          NaN         1
68       4910  37.066500  0.035500  2015                                                    Sphecidae Latreille, 1802  0.267927  46.898955  22.216203  0.183497 -0.009885 -0.009885  0.177402  37.658747  0.183497  3294.163086  26.110956  114.179909   2.207784  7.159570  0.175606       NaN  4.0          NaN         1
75       4726  37.176033 -0.698295  2015                                                        Paltothyreus tarsatus  0.800472  48.816951  59.150304  0.365406  0.333599  0.333599  0.468866  30.383431  0.365406   229.299637  30.558220  264.162476  19.835873  6.129761  0.212808  8.735840  1.0          NaN         1
76       4823  36.912315  0.032167  2015                                                         Camponotus maculatus  0.340832  45.377748  23.680966  0.114916 -0.071507 -0.071507  0.213818  40.401558  0.114916   231.493271  25.002163  249.506058   3.460222  7.103400  0.396991       NaN  4.0          NaN         1
77        763  37.000000 -0.633333  2015                                                      Tetramorium weitzeckeri  0.457889  46.870601  38.439988  0.301166  0.172751  0.172751  0.254148  32.952665  0.301166   542.269409  42.948906  204.373871  13.032513  5.407969  0.623312       NaN  2.0  1601.884766         1
79       4809  36.997833  0.012955  2015         Typhlopone fulvus (Westwood, 1839) = Dorylus fulvus (Westwood, 1839)  0.302241  46.449422  22.923981  0.151047 -0.084146 -0.084146  0.216448  38.956557  0.151047   204.191879  24.625547  162.345108   4.342700  6.976662  0.490733  6.152721  4.0          NaN         1
83       4238  37.251282 -0.103720  2015                                                               Apis mellifera   0.49695  50.232873  61.603912  0.747511  0.094075  0.094075   0.26215  15.101397  0.747511      0.00873  67.940941  332.252808  20.000950  5.954109  1.120987  1.858702  3.0          NaN         1
87       4910  37.105018  0.030616  2025                                                               Apis mellifera  0.416493  46.548586  31.322384  0.190647   0.06614   0.06614  0.245202  37.389479  0.190263  4915.071736  26.110956  114.179909   2.207784  7.159570  0.175606       NaN  3.0          NaN         1
92       4823  36.911973  0.032431  2025                                                               Apis mellifera    0.4013  47.837934  33.654009  0.198356 -0.073999 -0.073999  0.223141  37.081745  0.197956   243.841627  25.002163  249.506058   3.460222  7.103400  0.396991       NaN  3.0          NaN         1
96       4823  36.945717  0.003081  2025                                                           Ropalidia distigma    0.4013  47.837934  33.654009  0.198356 -0.073999 -0.073999  0.223141  37.081745  0.197956   243.841627  25.002163  249.506058   3.460222  7.103400  0.396991       NaN  3.0          NaN         1
98       4977  37.078623 -0.002880  2025                                                               Apis mellifera  0.687644  46.469858    50.5192  0.348584  0.257656  0.257656  0.396365  31.085325  0.347867  1198.538105  24.909851  255.342850   4.406862  7.022776  1.157296       NaN  3.0   975.350647         1
105      3616  36.633335 -0.416667  2025                     Ancistrocerus neuvillei (Buysson, 1906) subsp. neuvillei  0.637142   46.74625  59.109273  0.534998  0.128629  0.128629  0.378165  23.644464  0.533888          0.0  65.901711  152.626205   6.521485  5.651603  0.683296       NaN  2.0          NaN         1
111      4774  37.316666 -0.150000  2025                                                                dorylus indet   0.13172  44.705734        NaN       NaN -0.244397 -0.244397  0.043806        NaN       NaN     0.000252  47.315350  156.754334   7.426434  5.609660  2.212738  1.478975  2.0          NaN         1
112      1652  36.700001 -0.633333  2025                     Ancistrocerus neuvillei (Buysson, 1906) subsp. neuvillei  0.609114  45.613554  62.814145  0.666267  0.120315  0.120315  0.317188  18.404797   0.66488     0.014895  88.206161   54.340549  24.992153  5.652908  0.389679       NaN  1.0          NaN         1
113      4774  37.316667 -0.150000  2025                                                                  Platythyrea   0.13172  44.705734        NaN       NaN -0.244397 -0.244397  0.043806        NaN       NaN     0.000252  47.315350  156.754334   7.426434  5.609660  2.212738  1.478975  2.0          NaN         1
122      4802  37.040000  0.010000  2025                                         Pediobius foveolatus (Crawford 1912)  0.314425  46.756393  26.232028  0.167493 -0.072689 -0.072689  0.221326  38.313661  0.167158   847.672695  23.437033  169.881989   2.391154  6.690070  0.653344       NaN  3.0          NaN         1
123      3817  36.700000 -0.616670  2025                                                              dorylus (indet)  0.603847  45.634499  63.347906  0.671001  0.132533  0.132533   0.32099  18.215829  0.669604     0.004617  75.700218   29.663177  15.921447  5.700000  0.390253  1.900009  1.0          NaN         1
126        51  36.747690 -0.571770  2025                                Dorylus nigricans molestus (Gerstäcker, 1859)   0.80093  45.977845   76.10936  0.700262  0.300193  0.300193  0.470632  17.047847  0.698804      0.09948  79.425598  280.776154  13.095716  5.116456  2.134129       NaN  0.0          NaN         1
130      4774  37.308410 -0.152140  2025                                Dorylus nigricans molestus (Gerstäcker, 1859)   0.13172  44.705734        NaN       NaN -0.244397 -0.244397  0.043806        NaN       NaN     0.000252  47.315350  156.754334   7.426434  5.609660  2.212738  1.478975  2.0          NaN         1
131      4774  37.333332 -0.166667  2025                                            Synagris analis de Saussure, 1852   0.13172  44.705734        NaN       NaN -0.244397 -0.244397  0.043806        NaN       NaN     0.000252  47.315350  156.754334   7.426434  5.609660  2.212738  1.478975  2.0          NaN         1
134      4910  37.080460  0.015280  2025                                                   Andrena sp. Fabricius 1775  0.416493  46.548586  31.322384  0.190647   0.06614   0.06614  0.245202  37.389479  0.190263  4915.071736  26.110956  114.179909   2.207784  7.159570  0.175606       NaN  3.0          NaN         1

In [24]:
missing_summary = final[final.isna().any(axis=1)][
    ["OBJECTID", "Longitude", "Latitude", "year", "TaxonName",
     "VHI", "TCI", "LST", "SMI", "pop", "TWI", "rain"]
]

missing_summary

,OBJECTID,Longitude,Latitude,year,TaxonName,VHI,TCI,LST,SMI,pop,TWI,rain
0,763,37.000000,-0.633333,1995,polyrhachis viscosa,49.27619,0.40443,27.570998,0.40443,360.981494,NaN,1591.478027
1,763,37.000000,-0.633330,1995,tetraponera parops,49.27619,0.40443,27.570998,0.40443,360.981494,NaN,1591.478027
2,763,37.000000,-0.633330,1995,tetraponera ambigua,49.27619,0.40443,27.570998,0.40443,360.981494,NaN,1591.478027
3,763,37.000000,-0.633330,1995,tetraponera gerdae,49.27619,0.40443,27.570998,0.40443,360.981494,NaN,1591.478027
10,2544,36.635714,-0.546953,1995,"Anomma nigricans (Illiger, 1802) = Dorylus nig...",77.878495,0.774465,13.627992,0.774465,0.0,NaN,1730.248047
11,4593,37.219867,-0.664578,1995,"Anomma nigricans (Illiger, 1802) = Dorylus nig...",43.099125,0.337624,30.088249,0.337624,207.084081,8.696597,NaN
16,2544,36.635714,-0.546953,1995,"Technomyrmex detorquens (Walker, 1859) = Techn...",77.878495,0.774465,13.627992,0.774465,0.0,NaN,1730.248047
17,4377,37.300000,-0.150000,1995,Apis mellifera,46.311789,0.801169,12.62179,0.801169,0.001029,1.378922,NaN
18,4774,37.308410,-0.152140,1995,"Boltonopone soror (Emery, 1899)",57.66723,0.981676,5.82021,0.981676,0.00023,1.478975,NaN
19,4774,37.333332,-0.166667,1995,"Belonogaster pennata Richards, 1982",57.66723,0.981676,5.82021,0.981676,0.00023,1.478975,NaN
20,4758,37.233334,-0.416667,1995,"Ancistrocerus neuvillei (Buysson, 1906) subsp....",74.472339,0.64296,18.583141,0.64296,NaN,NaN,NaN
23,4252,37.300000,-0.270000,1995,Pteromalus Swederus 1795,62.60534,0.728589,15.356623,0.728589,0.00068,NaN,NaN
26,4823,36.913600,0.021800,2005,Distega carbonaria,49.762622,0.369885,30.204744,0.369885,219.799866,NaN,NaN
27,4823,36.913630,0.021770,2005,Aleiodes,49.762622,0.369885,30.204744,0.369885,219.799866,NaN,NaN
30,4823,36.913630,0.021700,2005,Cremnops,49.762622,0.369885,30.204744,0.369885,219.799866,NaN,NaN
46,4194,37.310223,-0.465306,2005,BOLD:ACE2866,72.059958,0.545147,23.194646,0.545147,15.11375,NaN,NaN
47,4194,37.310223,-0.465306,2005,BOLD:ADZ2287,72.059958,0.545147,23.194646,0.545147,15.11375,NaN,NaN
48,4194,37.310223,-0.465306,2005,BOLD:ACB7660,72.059958,0.545147,23.194646,0.545147,15.11375,NaN,NaN
50,4910,37.066667,0.016667,2005,"Megachile nasalis Smith, 1879",28.753335,0.170304,38.187496,0.170304,2209.459229,NaN,NaN
58,4809,36.997833,0.012955,2005,"Camponotus sp. (Mayr, 1861)",20.335179,0.073318,42.066713,0.073318,149.888016,6.152721,NaN
62,4956,36.903223,0.026475,2015,Sceliphron spirifex,37.787481,0.161286,38.547056,0.161286,269.598175,NaN,NaN
63,4956,36.903052,0.027349,2015,Apis mellifera scutellata,37.787481,0.161286,38.547056,0.161286,269.598175,NaN,NaN
64,4910,37.076938,0.002412,2015,Apis mellifera,22.216203,0.183497,37.658747,0.183497,3294.163086,NaN,NaN
68,4910,37.066500,0.035500,2015,"Sphecidae Latreille, 1802",22.216203,0.183497,37.658747,0.183497,3294.163086,NaN,NaN
75,4726,37.176033,-0.698295,2015,Paltothyreus tarsatus,59.150304,0.365406,30.383431,0.365406,229.299637,8.735840,NaN
76,4823,36.912315,0.032167,2015,Camponotus maculatus,23.680966,0.114916,40.401558,0.114916,231.493271,NaN,NaN
77,763,37.000000,-0.633333,2015,Tetramorium weitzeckeri,38.439988,0.301166,32.952665,0.301166,542.269409,NaN,1601.884766
79,4809,36.997833,0.012955,2015,"Typhlopone fulvus (Westwood, 1839) = Dorylus f...",22.923981,0.151047,38.956557,0.151047,204.191879,6.152721,NaN
83,4238,37.251282,-0.103720,2015,Apis mellifera,61.603912,0.747511,15.101397,0.747511,0.00873,1.858702,NaN
87,4910,37.105018,0.030616,2025,Apis mellifera,31.322384,0.190647,37.389479,0.190263,4915.071736,NaN,NaN
92,4823,36.911973,0.032431,2025,Apis mellifera,33.654009,0.198356,37.081745,0.197956,243.841627,NaN,NaN
96,4823,36.945717,0.003081,2025,Ropalidia distigma,33.654009,0.198356,37.081745,0.197956,243.841627,NaN,NaN
98,4977,37.078623,-0.002880,2025,Apis mellifera,50.5192,0.348584,31.085325,0.347867,1198.538105,NaN,975.350647
105,3616,36.633335,-0.416667,2025,"Ancistrocerus neuvillei (Buysson, 1906) subsp....",59.109273,0.534998,23.644464,0.533888,0.0,NaN,NaN
111,4774,37.316666,-0.150000,2025,dorylus indet,NaN,NaN,NaN,NaN,0.000252,1.478975,NaN
112,1652,36.700001,-0.633333,2025,"Ancistrocerus neuvillei (Buysson, 1906) subsp....",62.814145,0.666267,18.404797,0.66488,0.014895,NaN,NaN
113,4774,37.316667,-0.150000,2025,Platythyrea,NaN,NaN,NaN,NaN,0.000252,1.478975,NaN
122,4802,37.040000,0.010000,2025,Pediobius foveolatus (Crawford 1912),26.232028,0.167493,38.313661,0.167158,847.672695,NaN,NaN
123,3817,36.700000,-0.616670,2025,dorylus (indet),63.347906,0.671001,18.215829,0.669604,0.004617,1.900009,NaN
126,51,36.747690,-0.571770,2025,"Dorylus nigricans molestus (Gerstäcker, 1859)",76.10936,0.700262,17.047847,0.698804,0.09948,NaN,NaN
130,4774,37.308410,-0.152140,2025,"Dorylus nigricans molestus (Gerstäcker, 1859)",NaN,NaN,NaN,NaN,0.000252,1.478975,NaN
131,4774,37.333332,-0.166667,2025,"Synagris analis de Saussure, 1852",NaN,NaN,NaN,NaN,0.000252,1.478975,NaN
134,4910,37.080460,0.015280,2025,Andrena sp. Fabricius 1775,31.322384,0.190647,37.389479,0.190263,4915.071736,NaN,NaN

In [25]:
print("Missing records by year:")
print(
    final[final.isna().any(axis=1)]
    .groupby("year")
    .size()
)

print("\nMissing values by year and variable:")
print(
    final.groupby("year")[["VHI", "TCI", "LST", "SMI", "pop", "TWI", "rain"]]
    .apply(lambda x: x.isna().sum())
)

Missing records by year:
year
1995    12
2005     8
2015     9
2025    14
dtype: int64

Missing values by year and variable:
      VHI  TCI  LST  SMI  pop  TWI  rain
year
1995    0    0    0    0    1    8     6
2005    0    0    0    0    0    7     8
2015    0    0    0    0    0    6     8
2025    4    4    4    4    0    9    13

In [26]:
# Check the original condition-factor values for the affected OBJECTIDs
problem_ids = final.loc[
    final.isna().any(axis=1),
    "OBJECTID"
].dropna().unique()

problem_factors = factors[
    factors["OBJECTID"].isin(problem_ids)
].copy()

problem_factors[
    ["OBJECTID", "NDVI_1995", "TWI", "rain_1995",
     "VHI_2025", "TCI_2025", "LST_2025", "SMI_2025",
     "rain_2025"]
].sort_values("OBJECTID")

,OBJECTID,NDVI_1995,TWI,rain_1995,VHI_2025,TCI_2025,LST_2025,SMI_2025,rain_2025
50,51,0.752083,NaN,NaN,76.109360,0.700262,17.047847,0.698804,NaN
762,763,0.547744,NaN,1591.478027,50.834902,0.351596,30.965078,0.350873,1354.289063
1651,1652,0.551106,NaN,NaN,62.814145,0.666267,18.404797,0.664880,NaN
2543,2544,0.737784,NaN,1730.248047,76.247532,0.673032,18.134763,0.671631,1853.585815
3615,3616,0.574281,NaN,NaN,59.109273,0.534998,23.644464,0.533888,NaN
3816,3817,0.551835,1.900009,NaN,63.347906,0.671001,18.215829,0.669604,NaN
4193,4194,0.691308,NaN,NaN,72.795457,0.565250,22.436962,0.564076,NaN
4237,4238,0.545409,1.858702,NaN,61.901588,0.683617,17.712249,0.682194,NaN
4251,4252,0.493580,NaN,NaN,52.233007,0.534495,23.664541,0.533386,NaN
4376,4377,0.118741,1.378922,NaN,44.964694,0.743542,15.320331,0.741992,NaN
4592,4593,0.494370,8.696597,NaN,42.414223,0.213102,36.493179,0.212671,NaN
4725,4726,0.653292,8.735840,NaN,59.802706,0.343852,31.274174,0.343146,NaN
4757,4758,0.797410,NaN,NaN,71.690492,0.570272,22.236487,0.569088,NaN
4773,4774,0.167722,1.478975,NaN,NaN,NaN,NaN,NaN,NaN
4801,4802,0.377078,NaN,NaN,26.232028,0.167493,38.313661,0.167158,NaN
4808,4809,0.574102,6.152721,NaN,34.572684,0.179543,37.832701,0.179182,NaN
4822,4823,0.585891,NaN,NaN,33.654009,0.198356,37.081745,0.197956,NaN
4909,4910,0.456829,NaN,NaN,31.322384,0.190647,37.389479,0.190263,NaN
4955,4956,0.543876,NaN,NaN,47.003067,0.235570,35.596356,0.235091,NaN
4976,4977,0.596478,NaN,771.350403,50.519200,0.348584,31.085325,0.347867,975.350647

In [27]:
# Compare missing variables across all four years
check_ids = problem_ids

check = factors[factors["OBJECTID"].isin(check_ids)].copy()

cols_to_check = [
    "OBJECTID",
    "TWI",
    "rain_1995", "rain_2005", "rain_2015", "rain_2025",
    "VHI_1995", "VHI_2005", "VHI_2015", "VHI_2025",
    "TCI_1995", "TCI_2005", "TCI_2015", "TCI_2025",
    "LST_1995", "LST_2005", "LST_2015", "LST_2025",
    "SMI_1995", "SMI_2005", "SMI_2015", "SMI_2025"
]

check[cols_to_check].sort_values("OBJECTID")

,OBJECTID,TWI,rain_1995,rain_2005,rain_2015,rain_2025,VHI_1995,VHI_2005,VHI_2015,VHI_2025,...,TCI_2015,TCI_2025,LST_1995,LST_2005,LST_2015,LST_2025,SMI_1995,SMI_2005,SMI_2015,SMI_2025
50,51,NaN,NaN,NaN,NaN,NaN,79.200734,81.816677,73.348774,76.109360,...,0.675842,0.700262,13.204300,14.452343,17.967767,17.047847,0.785709,0.763718,0.675842,0.698804
762,763,NaN,1591.478027,1020.233826,1601.884766,1354.289063,49.276190,54.872740,38.439988,50.834902,...,0.301166,0.351596,27.570998,26.101153,32.952665,30.965078,0.404430,0.472480,0.301166,0.350873
1651,1652,NaN,NaN,NaN,NaN,NaN,61.519936,55.907362,56.025929,62.814145,...,0.580798,0.666267,18.478737,22.451515,21.768973,18.404797,0.645730,0.563727,0.580798,0.664880
2543,2544,NaN,1730.248047,1230.796143,1896.057983,1853.585815,77.878495,80.768762,73.399275,76.247532,...,0.652682,0.673032,13.627992,16.299498,18.894041,18.134763,0.774465,0.717536,0.652682,0.671631
3615,3616,NaN,NaN,NaN,NaN,NaN,62.595661,55.241501,51.958558,59.109273,...,0.508058,0.534998,18.596317,23.248344,24.678137,23.644464,0.642610,0.543805,0.508058,0.533888
3816,3817,1.900009,NaN,NaN,NaN,NaN,66.316781,56.489217,57.934333,63.347906,...,0.646666,0.671001,14.893012,20.441836,19.134649,18.215829,0.740892,0.613971,0.646666,0.669604
4193,4194,NaN,NaN,NaN,NaN,NaN,67.937784,72.059958,73.778618,72.795457,...,0.635092,0.565250,19.257814,23.194646,19.597526,22.436962,0.625054,0.545147,0.635092,0.564076
4237,4238,1.858702,NaN,NaN,NaN,NaN,69.582144,66.653509,61.603912,61.901588,...,0.747511,0.683617,12.174824,16.799862,15.101397,17.712249,0.813031,0.705026,0.747511,0.682194
4251,4252,NaN,NaN,NaN,NaN,NaN,62.605340,51.624522,48.225932,52.233007,...,0.494511,0.534495,15.356623,23.644997,25.219968,23.664541,0.728589,0.533888,0.494511,0.533386
4376,4377,1.378922,NaN,NaN,NaN,NaN,46.311789,42.422807,34.276445,44.964694,...,0.560737,0.743542,12.621790,14.596905,22.571292,15.320331,0.801169,0.760103,0.560737,0.741992
4592,4593,8.696597,NaN,NaN,NaN,NaN,43.099125,37.250398,49.187057,42.414223,...,0.287602,0.213102,30.088249,37.783543,33.495147,36.493179,0.337624,0.180404,0.287602,0.212671
4725,4726,8.735840,NaN,NaN,NaN,NaN,57.394248,55.224216,59.150304,59.802706,...,0.365406,0.343852,25.680822,30.082881,30.383431,31.274174,0.454594,0.372931,0.365406,0.343146
4757,4758,NaN,NaN,NaN,NaN,NaN,74.472339,72.765105,76.378782,71.690492,...,0.679806,0.570272,18.583141,22.387974,17.809216,22.236487,0.642960,0.565315,0.679806,0.569088
4773,4774,1.478975,NaN,NaN,NaN,NaN,57.667230,NaN,NaN,NaN,...,NaN,NaN,5.820210,NaN,NaN,NaN,0.981676,NaN,NaN,NaN
4801,4802,NaN,NaN,NaN,NaN,NaN,35.161591,18.400540,16.012881,26.232028,...,0.090697,0.167493,31.372010,40.951316,41.370202,38.313661,0.303555,0.101205,0.090697,0.167158
4808,4809,6.152721,NaN,NaN,NaN,NaN,51.242016,20.335179,22.923981,34.572684,...,0.151047,0.179543,27.145295,42.066713,38.956557,37.832701,0.415728,0.073318,0.151047,0.179182
4822,4823,NaN,NaN,NaN,NaN,NaN,54.468202,49.762622,23.680966,33.654009,...,0.114916,0.198356,25.186201,30.204744,40.401558,37.081745,0.467720,0.369885,0.114916,0.197956
4909,4910,NaN,NaN,NaN,NaN,NaN,41.807958,28.753335,22.216203,31.322384,...,0.183497,0.190647,29.557630,38.187496,37.658747,37.389479,0.351707,0.170304,0.183497,0.190263
4955,4956,NaN,NaN,NaN,NaN,NaN,48.657236,43.744402,37.787481,47.003067,...,0.161286,0.235570,27.882531,33.878694,38.547056,35.596356,0.396162,0.278030,0.161286,0.235091
4976,4977,NaN,771.350403,719.926697,753.145447,975.350647,57.244736,43.950357,41.386737,50.519200,...,0.308626,0.348584,23.517874,31.988267,32.654292,31.085325,0.511996,0.325294,0.308626,0.347867

In [28]:
# Save the merged occurrence + condition-factor dataset

output_file = "PHSI_Master_Occurrence_ConditionFactors.csv"

final.to_csv(output_file, index=False)

print("Saved successfully:")
print(output_file)

print("\nRecords:", len(final))
print("Columns:", len(final.columns))
print("\nColumns:")
print(final.columns.tolist())

Saved successfully:
PHSI_Master_Occurrence_ConditionFactors.csv

Records: 136
Columns: 24

Columns:
['OBJECTID', 'Longitude', 'Latitude', 'year', 'TaxonName', 'NDVI', 'PCI', 'VHI', 'TCI', 'NDBI', 'NDMI', 'SAVI', 'LST', 'SMI', 'pop', 'SOC', 'Aspect', 'Slope', 'PH', 'TRI', 'TWI', 'LULC', 'rain', 'Presence']

In [29]:
# Verify the saved file
check = pd.read_csv("PHSI_Master_Occurrence_ConditionFactors.csv")

print("Records:", len(check))
print("Columns:", len(check.columns))
print("Missing values:", check.isna().sum().sum())

Records: 136
Columns: 24
Missing values: 82

In [30]:
import pandas as pd

# Load the saved master dataset
final = pd.read_csv("PHSI_Master_Occurrence_ConditionFactors.csv")

# Load the original condition-factor dataset
factors = pd.read_csv("Condition_Factors.csv")

# Standardize OBJECTID
final["OBJECTID"] = pd.to_numeric(final["OBJECTID"], errors="coerce").astype("Int64")
factors["OBJECTID"] = pd.to_numeric(factors["OBJECTID"], errors="coerce").astype("Int64")

years = [1995, 2005, 2015, 2025]

background_list = []

for year in years:

    # Occurrence locations for this particular year
    occurrence_ids = set(
        final.loc[final["year"] == year, "OBJECTID"].dropna()
    )

    # Number of occurrence records in this year
    n_occurrence = len(final[final["year"] == year])

    # We want 2 background records for every occurrence
    n_background = n_occurrence * 2

    # Candidate locations excluding occurrence locations
    candidates = factors[
        ~factors["OBJECTID"].isin(occurrence_ids)
    ].copy()

    # Randomly select background locations
    background = candidates.sample(
        n=n_background,
        random_state=42 + year
    ).copy()

    # Add modelling information
    background["year"] = year
    background["TaxonName"] = "Background"
    background["Presence"] = 0

    background_list.append(background)

# Combine background data
background_all = pd.concat(
    background_list,
    ignore_index=True
)

print("Background records:", len(background_all))

print("\nBackground records by year:")
print(background_all.groupby("year").size())

Background records: 272

Background records by year:
year
1995     50
2005     74
2015     44
2025    104
dtype: int64

In [31]:
# Create the same 24-column structure for background records

background_final = background_all.copy()

# Create year-specific environmental variables
dynamic_variables = [
    "NDVI",
    "PCI",
    "VHI",
    "TCI",
    "NDBI",
    "NDMI",
    "SAVI",
    "LST",
    "SMI",
    "pop",
    "rain"
]

for var in dynamic_variables:
    background_final[var] = pd.NA
    
    for year in years:
        source_column = f"{var}_{year}"
        mask = background_final["year"] == year
        
        background_final.loc[mask, var] = (
            background_final.loc[mask, source_column]
        )

# Create year-specific LULC
background_final["LULC"] = pd.NA

for year in years:
    source_column = f"Nyeri_LULC_{year}"
    mask = background_final["year"] == year
    
    background_final.loc[mask, "LULC"] = (
        background_final.loc[mask, source_column]
    )

# Select exactly the same columns as the occurrence dataset
background_final = background_final[[
    "OBJECTID",
    "Longitude",
    "Latitude",
    "year",
    "TaxonName",
    "NDVI",
    "PCI",
    "VHI",
    "TCI",
    "NDBI",
    "NDMI",
    "SAVI",
    "LST",
    "SMI",
    "pop",
    "SOC",
    "Aspect",
    "Slope",
    "PH",
    "TRI",
    "TWI",
    "LULC",
    "rain",
    "Presence"
]]

print("Background records:", len(background_final))
print("Background columns:", len(background_final.columns))
print("\nColumns:")
print(background_final.columns.tolist())

Background records: 272
Background columns: 24

Columns:
['OBJECTID', 'Longitude', 'Latitude', 'year', 'TaxonName', 'NDVI', 'PCI', 'VHI', 'TCI', 'NDBI', 'NDMI', 'SAVI', 'LST', 'SMI', 'pop', 'SOC', 'Aspect', 'Slope', 'PH', 'TRI', 'TWI', 'LULC', 'rain', 'Presence']

In [32]:
print(background_final.head())

print("\nPresence values:")
print(background_final["Presence"].value_counts())

print("\nBackground records by year:")
print(background_final.groupby("year").size())

   OBJECTID  Longitude  Latitude  year   TaxonName NDVI  PCI  VHI  TCI NDBI  \
0      <NA>        NaN       NaN  1995  Background  NaN  NaN  0.0  NaN  0.0
1      <NA>        NaN       NaN  1995  Background  NaN  NaN  0.0  NaN  0.0
2      <NA>        NaN       NaN  1995  Background  NaN  NaN  0.0  NaN  0.0
3      <NA>        NaN       NaN  1995  Background  NaN  NaN  0.0  NaN  0.0
4      <NA>        NaN       NaN  1995  Background  NaN  NaN  0.0  NaN  0.0

   ...  pop SOC Aspect Slope  PH  TRI  TWI  LULC  rain  Presence
0  ...  NaN NaN    NaN   NaN NaN  NaN  NaN   NaN   NaN         0
1  ...  NaN NaN    NaN   NaN NaN  NaN  NaN   NaN   NaN         0
2  ...  NaN NaN    NaN   NaN NaN  NaN  NaN   NaN   NaN         0
3  ...  NaN NaN    NaN   NaN NaN  NaN  NaN   NaN   NaN         0
4  ...  NaN NaN    NaN   NaN NaN  NaN  NaN   NaN   NaN         0

[5 rows x 24 columns]

Presence values:
Presence
0    272
Name: count, dtype: int64

Background records by year:
year
1995     50
2005     74
2015     44
2025    104
dtype: int64

In [33]:
print(background_final.head())

print("\nMissing values:")
print(background_final.isna().sum())

print("\nPresence:")
print(background_final["Presence"].value_counts())

print("\nRecords by year:")
print(background_final.groupby("year").size())

   OBJECTID  Longitude  Latitude  year   TaxonName NDVI  PCI  VHI  TCI NDBI  \
0      <NA>        NaN       NaN  1995  Background  NaN  NaN  0.0  NaN  0.0
1      <NA>        NaN       NaN  1995  Background  NaN  NaN  0.0  NaN  0.0
2      <NA>        NaN       NaN  1995  Background  NaN  NaN  0.0  NaN  0.0
3      <NA>        NaN       NaN  1995  Background  NaN  NaN  0.0  NaN  0.0
4      <NA>        NaN       NaN  1995  Background  NaN  NaN  0.0  NaN  0.0

   ...  pop SOC Aspect Slope  PH  TRI  TWI  LULC  rain  Presence
0  ...  NaN NaN    NaN   NaN NaN  NaN  NaN   NaN   NaN         0
1  ...  NaN NaN    NaN   NaN NaN  NaN  NaN   NaN   NaN         0
2  ...  NaN NaN    NaN   NaN NaN  NaN  NaN   NaN   NaN         0
3  ...  NaN NaN    NaN   NaN NaN  NaN  NaN   NaN   NaN         0
4  ...  NaN NaN    NaN   NaN NaN  NaN  NaN   NaN   NaN         0

[5 rows x 24 columns]

Missing values:
OBJECTID     252
Longitude    252
Latitude     252
year           0
TaxonName      0
NDVI         252
PCI          252
VHI          203
TCI          252
NDBI           0
NDMI         252
SAVI         252
LST          252
SMI          252
pop          252
SOC          252
Aspect       252
Slope        252
PH           252
TRI          252
TWI          253
LULC         252
rain         253
Presence       0
dtype: int64

Presence:
Presence
0    272
Name: count, dtype: int64

Records by year:
year
1995     50
2005     74
2015     44
2025    104
dtype: int64

In [34]:
print("Condition-factor records:", len(factors))

print("\nFirst 5 OBJECTIDs:")
print(factors["OBJECTID"].head())

print("\nOBJECTID data type:")
print(factors["OBJECTID"].dtype)

print("\nMissing OBJECTIDs:")
print(factors["OBJECTID"].isna().sum())

print("\nFirst 5 rows:")
print(factors.head())

Condition-factor records: 65535

First 5 OBJECTIDs:
0    1
1    2
2    3
3    4
4    5
Name: OBJECTID, dtype: Int64

OBJECTID data type:
Int64

Missing OBJECTIDs:
60535

First 5 rows:
   OBJECTID  Longitude  Latitude  NDVI_1995  NDVI_2005  NDVI_2015  NDVI_2025  \
0         1  36.833259 -0.397848   0.770591   0.806752   0.837014   0.671456
1         2  36.794072 -0.296912   0.520596   0.493491   0.511073   0.549253
2         3  37.144445 -0.447023   0.638068   0.562411   0.455919   0.735100
3         4  36.674651 -0.485149   0.583268   0.549556   0.556273   0.643500
4         5  37.052083 -0.146314   0.523536   0.376470   0.389503   0.640413

    PCI_1995   PCI_2005   PCI_2015  ...       TRI       TWI  Nyeri_LULC_1995  \
0  40.618143  13.666149  43.679842  ...  0.691033  3.340299              1.0
1  39.798664  13.459880  42.701731  ...  1.146779  3.090171              2.0
2  42.097407  15.304171  48.914979  ...  0.164172  4.311491              4.0
3  39.554880  12.831272  41.642595  ...  0.094210  3.478228              3.0
4  39.129811  14.817998  46.964315  ...  0.796487  3.422947              4.0

   Nyeri_LULC_2005  Nyeri_LULC_2015  Nyeri_LULC_2025    rain_1995  \
0              0.0              1.0              2.0  1409.451416
1              4.0              2.0              3.0  1055.704468
2              1.0              2.0              1.0  1282.378296
3              2.0              3.0              1.0  1793.049072
4              4.0              4.0              3.0   925.801269

     rain_2005    rain_2015    rain_2025
0   982.221619  1468.854980  1604.407349
1   712.466614  1036.485840  1126.268311
2   828.974609  1384.858032  1239.576294
3  1274.396851  1882.766113  1922.106445
4   711.216309   838.181152   986.680969

[5 rows x 57 columns]

In [35]:
# Keep only valid spatial locations
factors_valid = factors[
    factors["OBJECTID"].notna()
].copy()

print("Valid condition-factor locations:", len(factors_valid))

print("\nFirst 5 OBJECTIDs:")
print(factors_valid["OBJECTID"].head())

print("\nLast 5 OBJECTIDs:")
print(factors_valid["OBJECTID"].tail())

print("\nMissing OBJECTIDs:")
print(factors_valid["OBJECTID"].isna().sum())

Valid condition-factor locations: 5000

First 5 OBJECTIDs:
0    1
1    2
2    3
3    4
4    5
Name: OBJECTID, dtype: Int64

Last 5 OBJECTIDs:
4995    4996
4996    4997
4997    4998
4998    4999
4999    5000
Name: OBJECTID, dtype: Int64

Missing OBJECTIDs:
0

In [36]:
years = [1995, 2005, 2015, 2025]

background_list = []

for year in years:

    # Occurrence locations for this year
    occurrence_ids = set(
        final.loc[
            final["year"] == year,
            "OBJECTID"
        ].dropna()
    )

    # Number of occurrence records
    n_occurrence = len(
        final[final["year"] == year]
    )

    # Two background records for every occurrence
    n_background = n_occurrence * 2

    # Valid candidate locations only
    candidates = factors_valid[
        ~factors_valid["OBJECTID"].isin(occurrence_ids)
    ].copy()

    # Randomly select background locations
    background = candidates.sample(
        n=n_background,
        random_state=42 + year
    ).copy()

    # Add modelling information
    background["year"] = year
    background["TaxonName"] = "Background"
    background["Presence"] = 0

    background_list.append(background)

# Combine all years
background_all = pd.concat(
    background_list,
    ignore_index=True
)

print("Background records:", len(background_all))

print("\nBackground records by year:")
print(background_all.groupby("year").size())

Background records: 272

Background records by year:
year
1995     50
2005     74
2015     44
2025    104
dtype: int64

In [37]:
print(background_all[
    ["OBJECTID", "Longitude", "Latitude", "year", "TaxonName", "Presence"]
].head(10))

print("\nMissing values in key fields:")
print(
    background_all[
        ["OBJECTID", "Longitude", "Latitude"]
    ].isna().sum()
)

   OBJECTID  Longitude  Latitude  year   TaxonName  Presence
0       525  36.941580 -0.551512  1995  Background         0
1      4443  37.166911 -0.432487  1995  Background         0
2      4452  37.177485 -0.423285  1995  Background         0
3       522  37.112742 -0.517694  1995  Background         0
4      1648  36.795565 -0.207470  1995  Background         0
5      3567  37.145821 -0.092390  1995  Background         0
6      1114  37.141734 -0.216899  1995  Background         0
7      2267  36.684756 -0.349376  1995  Background         0
8      4929  37.055402 -0.060117  1995  Background         0
9       306  36.778305 -0.123796  1995  Background         0

Missing values in key fields:
OBJECTID     0
Longitude    0
Latitude     0
dtype: int64

In [38]:
dynamic_variables = [
    "NDVI", "PCI", "VHI", "TCI", "NDBI",
    "NDMI", "SAVI", "LST", "SMI", "pop", "rain"
]

background_final_list = []

for year in years:

    # Select background records for this year
    bg = background_all[
        background_all["year"] == year
    ].copy()

    # Create the year-specific predictor columns
    for var in dynamic_variables:
        bg[var] = bg[f"{var}_{year}"]

    # Year-specific LULC
    bg["LULC"] = bg[f"Nyeri_LULC_{year}"]

    background_final_list.append(bg)

# Combine all years
background_final = pd.concat(
    background_final_list,
    ignore_index=True
)

# Keep exactly the same structure as the occurrence dataset
background_final = background_final[
    [
        "OBJECTID",
        "Longitude",
        "Latitude",
        "year",
        "TaxonName",
        "NDVI",
        "PCI",
        "VHI",
        "TCI",
        "NDBI",
        "NDMI",
        "SAVI",
        "LST",
        "SMI",
        "pop",
        "SOC",
        "Aspect",
        "Slope",
        "PH",
        "TRI",
        "TWI",
        "LULC",
        "rain",
        "Presence"
    ]
].copy()

print("Background records:", len(background_final))
print("Background columns:", len(background_final.columns))

print("\nFirst 5 background records:")
print(background_final.head())

Background records: 272
Background columns: 24

First 5 background records:
   OBJECTID  Longitude  Latitude  year   TaxonName      NDVI        PCI  \
0       525  36.941580 -0.551512  1995  Background  0.636007  40.723491
1      4443  37.166911 -0.432487  1995  Background  0.663094  42.167328
2      4452  37.177485 -0.423285  1995  Background  0.665279  42.191655
3       522  37.112742 -0.517694  1995  Background  0.405234  41.652707
4      1648  36.795565 -0.207470  1995  Background  0.525299  38.881251

         VHI       TCI      NDBI  ...          pop        SOC      Aspect  \
0  56.730903  0.459701  0.229289  ...  1619.729641  33.075653  287.402069
1  60.241271  0.501115  0.218419  ...   345.195834  36.085098   58.845901
2  60.936144  0.512690  0.210465  ...   234.948538  42.000000  116.603195
3  41.181042  0.394013 -0.014280  ...   510.682755  34.000000  175.167114
4  47.354597  0.389857 -0.004861  ...    50.645267  23.828167  151.370056

      Slope        PH       TRI       TWI  LULC         rain  Presence
0  2.987873  5.819578  0.521177  5.402206   3.0  2096.329102         0
1  2.896714  5.306837  0.413694  4.616071   3.0  1589.829834         0
2  7.071199  5.200000  0.267470  5.114917   4.0  1589.829834         0
3  6.376613  5.486420  0.953318  3.373833   2.0  1130.632202         0
4  4.997044  6.872529  0.419543  3.566511   3.0   805.786865         0

[5 rows x 24 columns]

In [39]:
print("\nMissing values:")
print(background_final.isna().sum())

print("\nRecords by year:")
print(background_final.groupby("year").size())

print("\nPresence:")
print(background_final["Presence"].value_counts())

Missing values:
OBJECTID      0
Longitude     0
Latitude      0
year          0
TaxonName     0
NDVI          1
PCI           0
VHI           1
TCI           1
NDBI          0
NDMI          1
SAVI          1
LST           1
SMI           1
pop           0
SOC           0
Aspect        0
Slope         0
PH            0
TRI           0
TWI           2
LULC          1
rain         12
Presence      0
dtype: int64

Records by year:
year
1995     50
2005     74
2015     44
2025    104
dtype: int64

Presence:
Presence
0    272
Name: count, dtype: int64

In [40]:
# Combine occurrence and background records
phsi_model_data = pd.concat(
    [final, background_final],
    ignore_index=True
)

print("Total modelling records:", len(phsi_model_data))
print("Total columns:", len(phsi_model_data.columns))

print("\nRecords by Presence:")
print(phsi_model_data["Presence"].value_counts())

print("\nRecords by year and Presence:")
print(
    phsi_model_data.groupby(
        ["year", "Presence"]
    ).size()
)

Total modelling records: 408
Total columns: 24

Records by Presence:
Presence
0    272
1    136
Name: count, dtype: int64

Records by year and Presence:
year  Presence
1995  0            50
      1            25
2005  0            74
      1            37
2015  0            44
      1            22
2025  0           104
      1            52
dtype: int64

In [41]:
# Check duplicate OBJECTIDs within each year
duplicates = (
    phsi_model_data
    .groupby(["year", "OBJECTID"])
    .size()
    .reset_index(name="count")
)

duplicates = duplicates[duplicates["count"] > 1]

print("Duplicate locations within the same year:")
print(len(duplicates))

# Check whether any background location overlaps an occurrence
occurrence_locations = set(
    zip(
        phsi_model_data.loc[
            phsi_model_data["Presence"] == 1, "year"
        ],
        phsi_model_data.loc[
            phsi_model_data["Presence"] == 1, "OBJECTID"
        ]
    )
)

background_locations = set(
    zip(
        phsi_model_data.loc[
            phsi_model_data["Presence"] == 0, "year"
        ],
        phsi_model_data.loc[
            phsi_model_data["Presence"] == 0, "OBJECTID"
        ]
    )
)

overlap = occurrence_locations.intersection(
    background_locations
)

print("\nOccurrence-background overlaps:")
print(len(overlap))

Duplicate locations within the same year:
31

Occurrence-background overlaps:
0

In [42]:
# Show the 31 duplicated year-location combinations
duplicate_details = phsi_model_data[
    phsi_model_data.duplicated(
        subset=["year", "OBJECTID"],
        keep=False
    )
].sort_values(
    ["year", "OBJECTID", "Presence", "TaxonName"]
)

print(duplicate_details[
    ["OBJECTID", "Longitude", "Latitude",
     "year", "TaxonName", "Presence"]
].to_string(index=False))

 OBJECTID  Longitude  Latitude  year                                                                   TaxonName  Presence
      597  37.130871 -0.131246  1995         Aneleus politus (Santschi, 1914) = Carebara polita (Santschi, 1914)         1
      597  37.130871 -0.131246  1995     Oligomyrmex politus (Santschi, 1914) = Carebara polita (Santschi, 1914)         1
      763  37.000000 -0.633333  1995                                                         polyrhachis viscosa         1
      763  37.000000 -0.633330  1995                                                         tetraponera ambigua         1
      763  37.000000 -0.633330  1995                                                          tetraponera gerdae         1
      763  37.000000 -0.633330  1995                                                          tetraponera parops         1
     1795  36.831490 -0.347810  1995                                                           discothyrea dryad         1
     1795  36.831490 -0.347810  1995                                                           hypoponera segnis         1
     1795  36.831490 -0.347810  1995                                                       strumigenys katapelta         1
     2121  36.935456 -0.420150  1995        Anomma nigricans (Illiger, 1802) = Dorylus nigricans (Illiger, 1802)         1
     2121  36.935456 -0.420150  1995                                          Technomyrmex albipes (Smith, 1861)         1
     2544  36.635714 -0.546953  1995        Anomma nigricans (Illiger, 1802) = Dorylus nigricans (Illiger, 1802)         1
     2544  36.635714 -0.546953  1995 Technomyrmex detorquens (Walker, 1859) = Technomyrmex albipes (Smith, 1861)         1
     4774  37.333332 -0.166667  1995                                         Belonogaster pennata Richards, 1982         1
     4774  37.308410 -0.152140  1995                                             Boltonopone soror (Emery, 1899)         1
      141  36.783857 -0.519183  2005                                                 Camponotus sp. (Mayr, 1861)         1
      141  36.783857 -0.519183  2005                                              Crematogaster sp. (Lund, 1831)         1
     1795  36.831490 -0.347810  2005                                                             aenictus weissi         1
     1795  36.831490 -0.347810  2005                                                        parasyscia afr-par13         1
     2012  36.635632 -0.385461  2005                                                          Polyrhachis medusa         1
     2012  36.635632 -0.385461  2005                                                     Tetramorium weitzeckeri         1
     3144  36.869090  0.024912  2005                                                         Sceliphron spirifex         1
     3144  36.876467 -0.002542  2005                                                         Tetraponera penzigi         1
     3477  37.010000 -0.150000  2005                                                      Aleiodes sp. BCLDQ0995         1
     3477  37.011060 -0.151280  2005                                                                BOLD:AAH8843         1
     4194  37.310223 -0.465306  2005                                                                BOLD:ACB7660         1
     4194  37.310223 -0.465306  2005                                                                BOLD:ACE2866         1
     4194  37.310223 -0.465306  2005                                                                BOLD:ADZ2287         1
     4362  37.309830 -0.380330  2005                                                              Camptothlipsis         1
     4362  37.311200 -0.383300  2005                                                             dorylus (indet)         1
     4533  37.250000 -0.483333  2005                                                             Dorylus molesta         1
     4533  37.282544 -0.502860  2005                                                  Euponera sp. (Forel, 1891)         1
     4803  37.066199 -0.040465  2005                                                              Apis mellifera         1
     4803  37.066333 -0.040320  2005                                                        Pheidole megacephala         1
     4811  37.084870 -0.007304  2005                                                              Apis mellifera         1
     4811  37.085033 -0.007304  2005                                                          Polistes africanus         1
     4823  36.913630  0.021770  2005                                                                    Aleiodes         1
     4823  36.913630  0.021700  2005                                                                    Cremnops         1
     4823  36.913600  0.021800  2005                                                          Distega carbonaria         1
     2695  36.664043 -0.525430  2015                                                              Apis mellifera         1
     2695  36.663828 -0.524929  2015                                                              Apis mellifera         1
     4196  37.234841 -0.454146  2015                                                              Apis mellifera         1
     4196  37.236385 -0.456910  2015                                                                    Synagris         1
     4196  37.236241 -0.456889  2015                                                          Xylocopa flavorufa         1
     4910  37.076938  0.002412  2015                                                              Apis mellifera         1
     4910  37.066500  0.035500  2015                                                   Sphecidae Latreille, 1802         1
     4956  36.903052  0.027349  2015                                                   Apis mellifera scutellata         1
     4956  36.903223  0.026475  2015                                                         Sceliphron spirifex         1
      166  36.950001 -0.416667  2025                                  Antepipona albocincta Giordani Soika, 1987         1
      166  36.950001 -0.416667  2025                                         Antepipona defracta (Buysson, 1906)         1
      166  36.950000 -0.416667  2025                                                          Cerceris andersoni         1
      166  36.950000 -0.416667  2025                                                         Cerceris erythroura         1
      166  36.950000 -0.416667  2025                                                             Cerceris yngvei         1
     1490  37.116670 -0.450000  2025                                                          Polyrhachis medusa         1
     1490  37.116670 -0.450000  2025                                                     Tetramorium weitzeckeri         1
     1490  37.116670 -0.450000  2025                                                       camponotus orinobates         1
     1510  36.850000 -0.283330  2025                                                      Pachycondyla berthoudi         1
     1510  36.850000 -0.283330  2025                                                         ophthalmopone ilgii         1
     2935  37.027813 -0.402077  2025                                                        camponotus maculatus         1
     2935  37.027813 -0.402077  2025                                                            dorylus buyssoni         1
     2935  37.027813 -0.402077  2025                                                   plectroctena mandibularis         1
     2935  37.027813 -0.402077  2025                                                           technomyrmex ilgi         1
     3802  36.958010 -0.437100  2025                               Dorylus nigricans molestus (Gerstäcker, 1859)         1
     3802  36.959753 -0.437249  2025                            Odynerus quattuordecimmaculatus Schulthess, 1913         1
     4101  36.900000 -0.400000  2025                                                     Myrmicaria opaciventris         1
     4101  36.900000 -0.400000  2025                                                          Polyrhachis medusa         1
     4101  36.900000 -0.400000  2025                                                     Tetramorium weitzeckeri         1
     4774  37.308410 -0.152140  2025                               Dorylus nigricans molestus (Gerstäcker, 1859)         1
     4774  37.316667 -0.150000  2025                                                                 Platythyrea         1
     4774  37.333332 -0.166667  2025                                           Synagris analis de Saussure, 1852         1
     4774  37.316666 -0.150000  2025                                                               dorylus indet         1
     4803  37.066012 -0.040159  2025                                                              Chrysis lincea         1
     4803  37.066085 -0.040161  2025                                                          Gronoceras felinum         1
     4803  37.066102 -0.040218  2025                                                             Polistes badius         1
     4803  37.066159 -0.040342  2025                                                             Polistes badius         1
     4823  36.911973  0.032431  2025                                                              Apis mellifera         1
     4823  36.945717  0.003081  2025                                                          Ropalidia distigma         1
     4910  37.080460  0.015280  2025                                                  Andrena sp. Fabricius 1775         1
     4910  37.105018  0.030616  2025                                                              Apis mellifera         1

In [43]:
background_duplicates = (
    background_final
    .groupby(["year", "OBJECTID"])
    .size()
    .reset_index(name="count")
)

background_duplicates = background_duplicates[
    background_duplicates["count"] > 1
]

print("Duplicate background locations within the same year:")
print(len(background_duplicates))

if len(background_duplicates) > 0:
    print("\nDuplicated background locations:")
    print(background_duplicates)

Duplicate background locations within the same year:
0

In [44]:
output_file = "PHSI_Final_Modelling_Dataset.csv"

phsi_model_data.to_csv(
    output_file,
    index=False
)

print("Saved successfully:")
print(output_file)

print("\nFinal dataset shape:")
print(phsi_model_data.shape)

Saved successfully:
PHSI_Final_Modelling_Dataset.csv

Final dataset shape:
(408, 24)

In [45]:
import pandas as pd

# Load datasets
conditions = pd.read_csv("Condition_Factors.csv")
occurrence = pd.read_csv("Occurance.csv")

# -------------------------------------------------------
# 1. Keep only the 5,000 valid spatial locations
# -------------------------------------------------------

conditions["OBJECTID"] = pd.to_numeric(
    conditions["OBJECTID"], errors="coerce"
).astype("Int64")

factors_valid = conditions[
    conditions["OBJECTID"].notna()
].copy()

print("Valid spatial locations:", len(factors_valid))


# -------------------------------------------------------
# 2. Define the four modelling years
# -------------------------------------------------------

years = [1995, 2005, 2015, 2025]


# -------------------------------------------------------
# 3. Variables that change by year
# -------------------------------------------------------

dynamic_variables = [
    "NDVI",
    "PCI",
    "VHI",
    "TCI",
    "NDBI",
    "NDMI",
    "SAVI",
    "LST",
    "SMI",
    "pop",
    "rain"
]


# -------------------------------------------------------
# 4. Variables that remain constant
# -------------------------------------------------------

static_variables = [
    "SOC",
    "Aspect",
    "Slope",
    "PH",
    "TRI",
    "TWI"
]


# -------------------------------------------------------
# 5. Create 5,000 records for each year
# -------------------------------------------------------

yearly_data = []

for year in years:

    df = factors_valid[
        ["OBJECTID", "Longitude", "Latitude"]
        + static_variables
    ].copy()

    # Add year
    df["year"] = year

    # Add year-specific dynamic variables
    for var in dynamic_variables:
        df[var] = factors_valid[f"{var}_{year}"]

    # Add year-specific LULC
    df["LULC"] = factors_valid[f"Nyeri_LULC_{year}"]

    yearly_data.append(df)


# Combine all four years
model_data = pd.concat(
    yearly_data,
    ignore_index=True
)


# -------------------------------------------------------
# 6. Add Presence information
# -------------------------------------------------------

occurrence["OBJECTID"] = pd.to_numeric(
    occurrence["OBJECTID"], errors="coerce"
).astype("Int64")

# Start with background = 0
model_data["Presence"] = 0


# Mark locations with occurrence records as presence = 1
occurrence_keys = set(
    zip(
        occurrence["OBJECTID"],
        occurrence["year"]
    )
)

model_data["Presence"] = [
    1 if (oid, year) in occurrence_keys else 0
    for oid, year in zip(
        model_data["OBJECTID"],
        model_data["year"]
    )
]


# -------------------------------------------------------
# 7. Check the result
# -------------------------------------------------------

print("\nFinal dataset shape:")
print(model_data.shape)

print("\nRecords by year:")
print(model_data["year"].value_counts().sort_index())

print("\nPresence counts:")
print(model_data["Presence"].value_counts())

print("\nPresence by year:")
print(
    model_data.groupby(
        ["year", "Presence"]
    ).size()
)

Valid spatial locations: 5000

Final dataset shape:
(20000, 23)

Records by year:
year
1995    5000
2005    5000
2015    5000
2025    5000
Name: count, dtype: int64

Presence counts:
Presence
0    19912
1       88
Name: count, dtype: int64

Presence by year:
year  Presence
1995  0           4984
      1             16
2005  0           4976
      1             24
2015  0           4983
      1             17
2025  0           4969
      1             31
dtype: int64

In [46]:
# Save the complete 20,000-record modelling dataset

output_file = "PHSI_Complete_5000Locations_4Years.csv"

model_data.to_csv(
    output_file,
    index=False
)

print("Saved successfully:")
print(output_file)

print("\nDataset shape:")
print(model_data.shape)

Saved successfully:
PHSI_Complete_5000Locations_4Years.csv

Dataset shape:
(20000, 23)

In [47]:
# Check missing values in every variable

missing_values = model_data.isna().sum()

print("Missing values by column:")
print(missing_values[missing_values > 0])

Missing values by column:
Aspect      20
Slope       20
PH           4
TWI        316
NDVI        18
PCI          3
VHI        128
TCI        147
NDMI        18
SAVI        18
LST        147
SMI        147
pop         26
rain      1100
LULC        18
dtype: int64

In [48]:
# Check missing values by year

missing_by_year = (
    model_data
    .groupby("year")
    .apply(lambda x: x.isna().sum(), include_groups=False)
)

print(missing_by_year)

      OBJECTID  Longitude  Latitude  SOC  Aspect  Slope  PH  TRI  TWI  NDVI  \
year
1995         0          0         0    0       5      5   1    0   79     1
2005         0          0         0    0       5      5   1    0   79    12
2015         0          0         0    0       5      5   1    0   79     1
2025         0          0         0    0       5      5   1    0   79     4

      ...  TCI  NDBI  NDMI  SAVI  LST  SMI  pop  rain  LULC  Presence
year  ...
1995  ...   22     0     1     1   22   22   13   275     1         0
2005  ...   56     0    12    12   56   56    0   275    12         0
2015  ...   41     0     1     1   41   41    0   275     1         0
2025  ...   28     0     4     4   28   28   13   275     4         0

[4 rows x 22 columns]

In [49]:
# Check missing values by year for the main variables

variables_to_check = [
    "Aspect",
    "Slope",
    "PH",
    "TWI",
    "NDVI",
    "PCI",
    "VHI",
    "TCI",
    "NDMI",
    "SAVI",
    "LST",
    "SMI",
    "pop",
    "rain",
    "LULC"
]

for year in [1995, 2005, 2015, 2025]:

    print(f"\n===== {year} =====")

    print(
        model_data.loc[
            model_data["year"] == year,
            variables_to_check
        ].isna().sum()
    )

===== 1995 =====
Aspect      5
Slope       5
PH          1
TWI        79
NDVI        1
PCI         1
VHI         0
TCI        22
NDMI        1
SAVI        1
LST        22
SMI        22
pop        13
rain      275
LULC        1
dtype: int64

===== 2005 =====
Aspect      5
Slope       5
PH          1
TWI        79
NDVI       12
PCI         0
VHI        62
TCI        56
NDMI       12
SAVI       12
LST        56
SMI        56
pop         0
rain      275
LULC       12
dtype: int64

===== 2015 =====
Aspect      5
Slope       5
PH          1
TWI        79
NDVI        1
PCI         1
VHI        39
TCI        41
NDMI        1
SAVI        1
LST        41
SMI        41
pop         0
rain      275
LULC        1
dtype: int64

===== 2025 =====
Aspect      5
Slope       5
PH          1
TWI        79
NDVI        4
PCI         1
VHI        27
TCI        28
NDMI        4
SAVI        4
LST        28
SMI        28
pop        13
rain      275
LULC        4
dtype: int64

In [50]:
# Check missing predictor values specifically at presence locations

predictors = [
    "NDVI",
    "PCI",
    "VHI",
    "TCI",
    "NDBI",
    "NDMI",
    "SAVI",
    "LST",
    "SMI",
    "pop",
    "SOC",
    "Aspect",
    "Slope",
    "PH",
    "TRI",
    "TWI",
    "LULC",
    "rain"
]

presence_data = model_data[
    model_data["Presence"] == 1
].copy()

print("Number of presence records:", len(presence_data))

print("\nMissing values among presence records:")
print(
    presence_data[predictors]
    .isna()
    .sum()
    .sort_values(ascending=False)
)

Number of presence records: 88

Missing values among presence records:
rain      23
TWI       18
pop        1
LST        1
VHI        1
TCI        1
SMI        1
NDVI       0
PCI        0
NDBI       0
SAVI       0
NDMI       0
SOC        0
Aspect     0
PH         0
Slope      0
TRI        0
LULC       0
dtype: int64

In [51]:
# Show the actual presence records that contain missing predictors

presence_missing = presence_data[
    presence_data[predictors].isna().any(axis=1)
]

print("Presence records with at least one missing predictor:")
print(len(presence_missing))

print("\nAffected presence records:")
print(
    presence_missing[
        ["OBJECTID", "Longitude", "Latitude", "year", "TaxonName"]
        + predictors
    ]
)

Presence records with at least one missing predictor:
27

Affected presence records:

KeyError: "['TaxonName'] not in index"

In [52]:
# Show presence locations with missing predictor values

presence_missing = presence_data[
    presence_data[predictors].isna().any(axis=1)
].copy()

print("Presence records with at least one missing predictor:")
print(len(presence_missing))

print("\nAffected presence records:")
print(
    presence_missing[
        ["OBJECTID", "Longitude", "Latitude", "year"]
        + predictors
    ].to_string(index=False)
)

Presence records with at least one missing predictor:
27

Affected presence records:
 OBJECTID  Longitude  Latitude  year     NDVI       PCI       VHI      TCI      NDBI      NDMI     SAVI       LST      SMI         pop       SOC     Aspect     Slope       PH      TRI      TWI  LULC        rain
      763  37.022924 -0.588006  1995 0.547744 40.565070 49.276190 0.404430  0.190476  0.190476 0.300664 27.570998 0.404430  360.981494 42.948906 204.373871 13.032513 5.407969 0.623312      NaN   4.0 1591.478027
     2544  36.665354 -0.534494  1995 0.737784 39.282827 77.878495 0.774465  0.190369  0.190369 0.388026 13.627992 0.774465    0.000000 64.713127 115.625153  7.896955 5.263845 0.785643      NaN   0.0 1730.248047
     4252  37.266493 -0.252522  1995 0.493580 41.162658 62.605340 0.728589  0.048044  0.048044 0.292732 15.356623 0.728589    0.000680 82.973686 171.246597 24.025703 5.324329 0.218313      NaN   2.0         NaN
     4377  37.298049 -0.148525  1995 0.118741 39.568740 46.311789 0.801169 -0.181554 -0.181554 0.042595 12.621790 0.801169    0.001029 44.341511 327.777222 38.848415 5.600000 2.836613 1.378922   2.0         NaN
     4593  37.170724 -0.627492  1995 0.494370 40.113191 43.099125 0.337624  0.075425  0.075425 0.329312 30.088249 0.337624  207.084081 35.148525  78.506844 18.150137 6.031483 0.459561 8.696597   4.0         NaN
     4758  37.210522 -0.400976  1995 0.797410 42.224791 74.472339 0.642960  0.398696  0.398696 0.476944 18.583141 0.642960         NaN 51.375164 208.758270  9.942536 5.300000 0.540889      NaN   1.0         NaN
     4774  37.302405 -0.152386  1995 0.167722 39.636415 57.667230 0.981676 -0.218344 -0.218344 0.034226  5.820210 0.981676    0.000230 47.315350 156.754334  7.426434 5.609660 2.212738 1.478975   2.0         NaN
     4194  37.204791 -0.413786  2005 0.816875 15.621821 72.059958 0.545147  0.352071  0.352071 0.466129 23.194646 0.545147   15.113750 47.284016 156.408356  7.988733 5.235861 0.853780      NaN   0.0         NaN
     4809  37.045700 -0.019837  2005 0.319454 14.784978 20.335179 0.073318 -0.142939 -0.142939 0.209174 42.066713 0.073318  149.888016 24.625547 162.345108  4.342700 6.976662 0.490733 6.152721   4.0         NaN
     4823  36.982433 -0.071906  2005 0.579919 14.451371 49.762622 0.369885  0.103995  0.103995 0.351614 30.204744 0.369885  219.799866 25.002163 249.506058  3.460222 7.103400 0.396991      NaN   1.0         NaN
     4910  37.073520  0.007806  2005 0.389213 14.930837 28.753335 0.170304 -0.004664 -0.004664 0.242506 38.187496 0.170304 2209.459229 26.110956 114.179909  2.207784 7.159570 0.175606      NaN   4.0         NaN
      763  37.022924 -0.588006  2015 0.457889 46.870601 38.439988 0.301166  0.172751  0.172751 0.254148 32.952665 0.301166  542.269409 42.948906 204.373871 13.032513 5.407969 0.623312      NaN   2.0 1601.884766
     4238  37.251822 -0.116594  2015 0.496950 50.232873 61.603912 0.747511  0.094075  0.094075 0.262150 15.101397 0.747511    0.008730 67.940941 332.252808 20.000950 5.954109 1.120987 1.858702   3.0         NaN
     4726  37.165484 -0.633620  2015 0.800472 48.816951 59.150304 0.365406  0.333599  0.333599 0.468866 30.383431 0.365406  229.299637 30.558220 264.162476 19.835873 6.129761 0.212808 8.735840   1.0         NaN
     4809  37.045700 -0.019837  2015 0.302241 46.449422 22.923981 0.151047 -0.084146 -0.084146 0.216448 38.956557 0.151047  204.191879 24.625547 162.345108  4.342700 6.976662 0.490733 6.152721   4.0         NaN
     4823  36.982433 -0.071906  2015 0.340832 45.377748 23.680966 0.114916 -0.071507 -0.071507 0.213818 40.401558 0.114916  231.493271 25.002163 249.506058  3.460222 7.103400 0.396991      NaN   4.0         NaN
     4910  37.073520  0.007806  2015 0.267927 46.898955 22.216203 0.183497 -0.009885 -0.009885 0.177402 37.658747 0.183497 3294.163086 26.110956 114.179909  2.207784 7.159570 0.175606      NaN   4.0         NaN
     4956  36.979943 -0.073755  2015 0.516521 45.334882 37.787481 0.161286  0.089899  0.089899 0.333192 38.547056 0.161286  269.598175 25.000000 200.576340  3.073024 7.113849 0.997912      NaN   4.0         NaN
       51  36.744437 -0.565939  2025 0.800930 45.977845 76.109360 0.700262  0.300193  0.300193 0.470632 17.047847 0.698804    0.099480 79.425598 280.776154 13.095716 5.116456 2.134129      NaN   0.0         NaN
     1652  36.708625 -0.620954  2025 0.609114 45.613554 62.814145 0.666267  0.120315  0.120315 0.317188 18.404797 0.664880    0.014895 88.206161  54.340549 24.992153 5.652908 0.389679      NaN   1.0         NaN
     3616  36.636348 -0.412996  2025 0.637142 46.746250 59.109273 0.534998  0.128629  0.128629 0.378165 23.644464 0.533888    0.000000 65.901711 152.626205  6.521485 5.651603 0.683296      NaN   2.0         NaN
     3817  36.705690 -0.611133  2025 0.603847 45.634499 63.347906 0.671001  0.132533  0.132533 0.320990 18.215829 0.669604    0.004617 75.700218  29.663177 15.921447 5.700000 0.390253 1.900009   1.0         NaN
     4774  37.302405 -0.152386  2025 0.131720 44.705734       NaN      NaN -0.244397 -0.244397 0.043806       NaN      NaN    0.000252 47.315350 156.754334  7.426434 5.609660 2.212738 1.478975   2.0         NaN
     4802  37.061296  0.001126  2025 0.314425 46.756393 26.232028 0.167493 -0.072689 -0.072689 0.221326 38.313661 0.167158  847.672695 23.437033 169.881989  2.391154 6.690070 0.653344      NaN   3.0         NaN
     4823  36.982433 -0.071906  2025 0.401300 47.837934 33.654009 0.198356 -0.073999 -0.073999 0.223141 37.081745 0.197956  243.841627 25.002163 249.506058  3.460222 7.103400 0.396991      NaN   3.0         NaN
     4910  37.073520  0.007806  2025 0.416493 46.548586 31.322384 0.190647  0.066140  0.066140 0.245202 37.389479 0.190263 4915.071736 26.110956 114.179909  2.207784 7.159570 0.175606      NaN   3.0         NaN
     4977  37.080072 -0.003584  2025 0.687644 46.469858 50.519200 0.348584  0.257656  0.257656 0.396365 31.085325 0.347867 1198.538105 24.909851 255.342850  4.406862 7.022776 1.157296      NaN   3.0  975.350647

In [53]:
# ============================================================
# STEP 5: CHECK DATA TYPES AND PREDICTOR STRUCTURE
# ============================================================

predictors = [
    "NDVI",
    "PCI",
    "VHI",
    "TCI",
    "NDBI",
    "NDMI",
    "SAVI",
    "LST",
    "SMI",
    "pop",
    "SOC",
    "Aspect",
    "Slope",
    "PH",
    "TRI",
    "TWI",
    "LULC",
    "rain"
]

print("DATA TYPES")
print("=" * 50)

print(model_data[predictors].dtypes)


print("\n\nUNIQUE LULC VALUES")
print("=" * 50)

print(
    model_data["LULC"]
    .value_counts(dropna=False)
    .sort_index()
)


print("\n\nTARGET VARIABLE")
print("=" * 50)

print(model_data["Presence"].value_counts())


print("\n\nYEAR")
print("=" * 50)

print(model_data["year"].value_counts().sort_index())

DATA TYPES
==================================================
NDVI      float64
PCI       float64
VHI       float64
TCI       float64
NDBI      float64
NDMI      float64
SAVI      float64
LST       float64
SMI       float64
pop       float64
SOC       float64
Aspect    float64
Slope     float64
PH        float64
TRI       float64
TWI       float64
LULC      float64
rain      float64
dtype: object


UNIQUE LULC VALUES
==================================================
LULC
0.0    5227
1.0    2875
2.0    3530
3.0    4334
4.0    4016
NaN      18
Name: count, dtype: int64


TARGET VARIABLE
==================================================
Presence
0    19912
1       88
Name: count, dtype: int64


YEAR
==================================================
year
1995    5000
2005    5000
2015    5000
2025    5000
Name: count, dtype: int64

In [54]:
# ============================================================
# STEP 6: PREPARE MODEL DATA
# ============================================================

import pandas as pd

# Predictor variables
predictors = [
    "NDVI",
    "PCI",
    "VHI",
    "TCI",
    "NDBI",
    "NDMI",
    "SAVI",
    "LST",
    "SMI",
    "pop",
    "SOC",
    "Aspect",
    "Slope",
    "PH",
    "TRI",
    "TWI",
    "LULC",
    "rain"
]

# Create modelling dataframe
X = model_data[predictors].copy()

# Target
y = model_data["Presence"].copy()

print("Predictor matrix shape:", X.shape)
print("Target shape:", y.shape)

print("\nPredictors:")
print(list(X.columns))

print("\nTarget distribution:")
print(y.value_counts())

Predictor matrix shape: (20000, 18)
Target shape: (20000,)

Predictors:
['NDVI', 'PCI', 'VHI', 'TCI', 'NDBI', 'NDMI', 'SAVI', 'LST', 'SMI', 'pop', 'SOC', 'Aspect', 'Slope', 'PH', 'TRI', 'TWI', 'LULC', 'rain']

Target distribution:
Presence
0    19912
1       88
Name: count, dtype: int64

In [55]:
# Check whether XGBoost is installed

try:
    import xgboost as xgb
    print("XGBoost is installed.")
    print("Version:", xgb.__version__)
except ImportError:
    print("XGBoost is NOT installed.")

XGBoost is NOT installed.